spring:
  profiles:
    active: dev
  security:
#    user:
#      name: bbz
#      password: bbz
#      roles: USER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_demo?useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: liulaoye
#  jackson:
#    serialization:
#      write_dates_as_timestamps: false
server:
  port: 8000

bbz:
  security:
    code:
      image:
        length: 4
#        width: 100
      sms:
        length: 6
        url: /user/*


    browser:
      t: t
#      loginType: REDIRECT
#      loginPage: /demo-signin.html
#  spring.jackson.serialization.write_dates_as_timestamps=false